// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.3
// source: catAnalysis.proto

package proto

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type AnalysisRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CatName string `protobuf:"bytes,1,opt,name=catName,proto3" json:"catName,omitempty"`
}

func (x *AnalysisRequest) Reset() {
	*x = AnalysisRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_catAnalysis_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AnalysisRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalysisRequest) ProtoMessage() {}

func (x *AnalysisRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catAnalysis_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalysisRequest.ProtoReflect.Descriptor instead.
func (*AnalysisRequest) Descriptor() ([]byte, []int) {
	return file_catAnalysis_proto_rawDescGZIP(), []int{0}
}

func (x *AnalysisRequest) GetCatName() string {
	if x != nil {
		return x.CatName
	}
	return ""
}

type AnalysisResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *AnalysisResponse) Reset() {
	*x = AnalysisResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_catAnalysis_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AnalysisResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalysisResponse) ProtoMessage() {}

func (x *AnalysisResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catAnalysis_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalysisResponse.ProtoReflect.Descriptor instead.
func (*AnalysisResponse) Descriptor() ([]byte, []int) {
	return file_catAnalysis_proto_rawDescGZIP(), []int{1}
}

func (x *AnalysisResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

var File_catAnalysis_proto protoreflect.FileDescriptor

var file_catAnalysis_proto_rawDesc = []byte{
	0x0a, 0x11, 0x63, 0x61, 0x74, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x69, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2b, 0x0a, 0x0f, 0x41, 0x6e,
	0x61, 0x6c, 0x79, 0x73, 0x69, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a,
	0x07, 0x63, 0x61, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x63, 0x61, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x2a, 0x0a, 0x10, 0x41, 0x6e, 0x61, 0x6c, 0x79,
	0x73, 0x69, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x32, 0x50, 0x0a, 0x0b, 0x63, 0x61, 0x74, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x73,
	0x69, 0x73, 0x12, 0x41, 0x0a, 0x0c, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x7a, 0x65, 0x53, 0x6f, 0x75,
	0x6e, 0x64, 0x12, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x6e, 0x61, 0x6c, 0x79,
	0x73, 0x69, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x69, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_catAnalysis_proto_rawDescOnce sync.Once
	file_catAnalysis_proto_rawDescData = file_catAnalysis_proto_rawDesc
)

func file_catAnalysis_proto_rawDescGZIP() []byte {
	file_catAnalysis_proto_rawDescOnce.Do(func() {
		file_catAnalysis_proto_rawDescData = protoimpl.X.CompressGZIP(file_catAnalysis_proto_rawDescData)
	})
	return file_catAnalysis_proto_rawDescData
}

var file_catAnalysis_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_catAnalysis_proto_goTypes = []interface{}{
	(*AnalysisRequest)(nil),  // 0: proto.AnalysisRequest
	(*AnalysisResponse)(nil), // 1: proto.AnalysisResponse
}
var file_catAnalysis_proto_depIdxs = []int32{
	0, // 0: proto.catAnalysis.AnalyzeSound:input_type -> proto.AnalysisRequest
	1, // 1: proto.catAnalysis.AnalyzeSound:output_type -> proto.AnalysisResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_catAnalysis_proto_init() }
func file_catAnalysis_proto_init() {
	if File_catAnalysis_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_catAnalysis_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AnalysisRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_catAnalysis_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AnalysisResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_catAnalysis_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_catAnalysis_proto_goTypes,
		DependencyIndexes: file_catAnalysis_proto_depIdxs,
		MessageInfos:      file_catAnalysis_proto_msgTypes,
	}.Build()
	File_catAnalysis_proto = out.File
	file_catAnalysis_proto_rawDesc = nil
	file_catAnalysis_proto_goTypes = nil
	file_catAnalysis_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// CatAnalysisClient is the client API for CatAnalysis service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CatAnalysisClient interface {
	AnalyzeSound(ctx context.Context, in *AnalysisRequest, opts ...grpc.CallOption) (*AnalysisResponse, error)
}

type catAnalysisClient struct {
	cc grpc.ClientConnInterface
}

func NewCatAnalysisClient(cc grpc.ClientConnInterface) CatAnalysisClient {
	return &catAnalysisClient{cc}
}

func (c *catAnalysisClient) AnalyzeSound(ctx context.Context, in *AnalysisRequest, opts ...grpc.CallOption) (*AnalysisResponse, error) {
	out := new(AnalysisResponse)
	err := c.cc.Invoke(ctx, "/proto.catAnalysis/AnalyzeSound", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CatAnalysisServer is the server API for CatAnalysis service.
type CatAnalysisServer interface {
	AnalyzeSound(context.Context, *AnalysisRequest) (*AnalysisResponse, error)
}

// UnimplementedCatAnalysisServer can be embedded to have forward compatible implementations.
type UnimplementedCatAnalysisServer struct {
}

func (*UnimplementedCatAnalysisServer) AnalyzeSound(context.Context, *AnalysisRequest) (*AnalysisResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AnalyzeSound not implemented")
}

func RegisterCatAnalysisServer(s *grpc.Server, srv CatAnalysisServer) {
	s.RegisterService(&_CatAnalysis_serviceDesc, srv)
}

func _CatAnalysis_AnalyzeSound_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalysisRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatAnalysisServer).AnalyzeSound(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.catAnalysis/AnalyzeSound",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatAnalysisServer).AnalyzeSound(ctx, req.(*AnalysisRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CatAnalysis_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.catAnalysis",
	HandlerType: (*CatAnalysisServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AnalyzeSound",
			Handler:    _CatAnalysis_AnalyzeSound_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "catAnalysis.proto",
}
