# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import cat_pb2 as cat__pb2


class catStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CallCat = channel.unary_unary(
                '/proto.cat/CallCat',
                request_serializer=cat__pb2.CatRequest.SerializeToString,
                response_deserializer=cat__pb2.CatResponse.FromString,
                )
        self.AnalyzeCatSound = channel.unary_stream(
                '/proto.cat/AnalyzeCatSound',
                request_serializer=cat__pb2.AnalyzeCatSoundRequest.SerializeToString,
                response_deserializer=cat__pb2.AnalyzeCatSoundResponse.FromString,
                )


class catServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CallCat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AnalyzeCatSound(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_catServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CallCat': grpc.unary_unary_rpc_method_handler(
                    servicer.CallCat,
                    request_deserializer=cat__pb2.CatRequest.FromString,
                    response_serializer=cat__pb2.CatResponse.SerializeToString,
            ),
            'AnalyzeCatSound': grpc.unary_stream_rpc_method_handler(
                    servicer.AnalyzeCatSound,
                    request_deserializer=cat__pb2.AnalyzeCatSoundRequest.FromString,
                    response_serializer=cat__pb2.AnalyzeCatSoundResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'proto.cat', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class cat(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CallCat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.cat/CallCat',
            cat__pb2.CatRequest.SerializeToString,
            cat__pb2.CatResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AnalyzeCatSound(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/proto.cat/AnalyzeCatSound',
            cat__pb2.AnalyzeCatSoundRequest.SerializeToString,
            cat__pb2.AnalyzeCatSoundResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
