# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import dog_pb2 as dog__pb2


class dogStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CallDog = channel.unary_unary(
                '/proto.dog/CallDog',
                request_serializer=dog__pb2.DogRequest.SerializeToString,
                response_deserializer=dog__pb2.DogResponse.FromString,
                )


class dogServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CallDog(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_dogServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CallDog': grpc.unary_unary_rpc_method_handler(
                    servicer.CallDog,
                    request_deserializer=dog__pb2.DogRequest.FromString,
                    response_serializer=dog__pb2.DogResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'proto.dog', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class dog(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CallDog(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.dog/CallDog',
            dog__pb2.DogRequest.SerializeToString,
            dog__pb2.DogResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
