# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import catAnalysis_pb2 as catAnalysis__pb2


class catAnalysisStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AnalyzeSound = channel.unary_unary(
                '/proto.catAnalysis/AnalyzeSound',
                request_serializer=catAnalysis__pb2.AnalysisRequest.SerializeToString,
                response_deserializer=catAnalysis__pb2.AnalysisResponse.FromString,
                )


class catAnalysisServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AnalyzeSound(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_catAnalysisServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AnalyzeSound': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeSound,
                    request_deserializer=catAnalysis__pb2.AnalysisRequest.FromString,
                    response_serializer=catAnalysis__pb2.AnalysisResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'proto.catAnalysis', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class catAnalysis(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AnalyzeSound(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.catAnalysis/AnalyzeSound',
            catAnalysis__pb2.AnalysisRequest.SerializeToString,
            catAnalysis__pb2.AnalysisResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
